'''
DO NOT DELETE OR MOVE THIS FILE PLS
THIS FILE IS USED TO DECLARE THAT THE DIRECTORY CONTAINING IT
IS A PACKAGE OF OUR PROJECT

IT ALLOWS TO IMPORT CLASSES LIKE THAT
from package.fileName import ClassName
'''
